steps:
  - name: 'python'
    id: 'Requirements'
    args: ['pip3', 'install', '-r', 'requirements.txt', '--user']

  - name: "ubuntu"
    args: ["bash", "./cloud_env.sh"]
    env:
      - CONTRACT_ADDRESS=$_CONTRACT_ADDRESS
      - DB_INFO=$_DB_INFO
      - PRIVATE_KEY=$_PRIVATE_KEY
      - PUBLIC_KEY=$_PUBLIC_KEY
      - SERVER_ADDRESS=$_SERVER_ADDRESS

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy'
    args: ['app', 'deploy']

timeout: '600s'
